### ISSUE TITLE
Sprint Goals

### ISSUE THREAD

**Issue by indocomsoft** [source-academy/cadet#37]
Here be sprint goals. Include the PR number in parantheses.

# Sprint 1
APIfy everything!
- [x] Transform current repo into REST API, JSON (#32, #33)
  - [x] In-Progress
  - [x] Under Review
  - [x] Done
- [ ] Finish up `Assessment` context (#34, #35)
  - [x] In-Progress
  - [x] Under Review
  - [ ] Done
- [x] Use `swagger` to do API documentation (#31)
  - [x] In-Progress
  - [x] Under Review
  - [x] Done

# Sprint 2
Review process: review each other before asking for Evan's review.
Focus on the public facing stuffs, finish up basic flow w.r.t. missions
- [ ] Submission by student
  - [ ] In-Progress
  - [ ] Under Review
  - [ ] Done
- [ ] Grading by tutor
  - [ ] In-Progress
  - [ ] Under Review
  - [ ] Done
- [ ] IVLE login stuffs (processing IVLE token)
  - [ ] In-Progress
  - [ ] Under Review
  - [ ] Done
## Low priority
- [ ] Pulling data from git to create missions
  - [ ] In-Progress
  - [ ] Under Review
  - [ ] Done
